import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Lucas",
      email: "lumas9@gmail.com",
      password: bcrypt.hashSync("1147", 8),
      isAdmin: true,
    },
    {
      name: "Jonh",
      email: "johasn@gmail.com",
      password: bcrypt.hashSync("1247", 8),
      isAdmin: false,
    },
    {
      name: "Maxu",
      email: "max@gmail.com",
      password: bcrypt.hashSync("1247", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Moto E5",
      category: "Celulares",
      image: "/images/p2.jpg",
      price: 18000,
      countInStock: 10,
      brand: "Motorola",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Moto E6",
      category: "Celulares",
      image: "/images/p1.jpg",
      price: 19950,
      countInStock: 20,
      brand: "Motorola",
      rating: 3.8,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Moto G5",
      category: "Celulares",
      image: "/images/p3.jpg",
      price: 22000,
      countInStock: 0,
      brand: "Motorola",
      rating: 4.0,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Moto G6",
      category: "Celulares",
      image: "/images/p4.jpg",
      price: 28000,
      countInStock: 5,
      brand: "Motorola",
      rating: 4.1,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Moto G7",
      category: "Celulares",
      image: "/images/p5.jpg",
      price: 31000,
      countInStock: 5,
      brand: "Motorola",
      rating: 4.3,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Moto G8",
      category: "Celulares",
      image: "/images/p6.jpg",
      price: 45000,
      countInStock: 15,
      brand: "Motorola",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
