const data = {
    products: [
      {
        _id: '1',
        name: 'Moto E5',
        category: 'Celulares',
        image: '/images/p2.jpg',
        price: 120,
        brand: 'Motorola',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Moto E6',
        category: 'Celulares',
        image: '/images/p1.jpg',
        price: 100,
        brand: 'Motorola',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Moto G5',
        category: 'Celulares',
        image: '/images/p3.jpg',
        price: 220,
        brand: 'Motorola',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Moto G6',
        category: 'Celulares',
        image: '/images/p4.jpg',
        price: 78,
        brand: 'Motorola',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Moto G7',
        category: 'Celulares',
        image: '/images/p5.jpg',
        price: 65,
        brand: 'Motorola',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Moto G8',
        category: 'Celulares',
        image: '/images/p6.jpg',
        price: 139,
        brand: 'Motorola',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;
  